/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Fornecedor;
import model.dao.FornecedorDAO;
import model.dao.UsuarioLoginDao;


/**
 *
 * @author artur
 */
public class ScreenFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ScreenFornecedor2
     */
    public ScreenFornecedor() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }

    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();

        for (Fornecedor f : fdao.read()) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazao_social(),
                f.getNome_fantasia(),
                f.getCnpj()
            });

        }

    }
    
    public void readJTableRazaoSocial(String razaoS) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();

        for (Fornecedor f : fdao.readRazaoSocial(razaoS)) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazao_social(),
                f.getNome_fantasia(),
                f.getCnpj()
            });

        }

    }
    
    public void readJTableCNPJ(String cnpj) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();

        for (Fornecedor f : fdao.readCNPJ(cnpj)) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazao_social(),
                f.getNome_fantasia(),
                f.getCnpj()
            });

        }

    }
    
    public void readJTableFantasia(String fantasia) {
        
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setNumRows(0);
        FornecedorDAO fdao = new FornecedorDAO();

        for (Fornecedor f : fdao.readFantasia(fantasia)) {

            modelo.addRow(new Object[]{
                f.getId(),
                f.getRazao_social(),
                f.getNome_fantasia(),
                f.getCnpj()
            });

        }

    }
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        ImageIcon icon = new ImageIcon(getClass().getResource("/img/background_fornecedor.png"));
        Image image = icon.getImage();
        jPanel1 = new javax.swing.JPanel(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRazaoS = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFantasia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCNPJ = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        ComboEstado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtCep = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setClosable(true);
        setTitle("Fornecedor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setLayout(null);

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jInternalFrame2.setVisible(false);
        jInternalFrame2.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame2InternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        jInternalFrame2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Razão Social*");
        jInternalFrame2.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, -1, -1));

        jLabel4.setText("Nome Fantasia*");
        jInternalFrame2.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 100, -1, -1));
        jInternalFrame2.getContentPane().add(txtRazaoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, 264, -1));
        jInternalFrame2.getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 181, 110, -1));
        jInternalFrame2.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 100, -1, -1));
        jInternalFrame2.getContentPane().add(txtFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 123, 551, -1));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("* Campo Obrigatoriio");
        jInternalFrame2.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel7.setText("Endereço* ");
        jInternalFrame2.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 158, -1, -1));
        jInternalFrame2.getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 181, 423, -1));

        jLabel8.setText("Numero*");
        jInternalFrame2.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 158, -1, -1));
        jInternalFrame2.getContentPane().add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 71, 249, -1));

        jLabel9.setText("Bairro* ");
        jInternalFrame2.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, -1, -1));
        jInternalFrame2.getContentPane().add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 239, 240, -1));

        jLabel10.setText("Complemento");
        jInternalFrame2.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 216, 85, -1));
        jInternalFrame2.getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 239, 293, -1));

        jLabel11.setText("Estado*");
        jInternalFrame2.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 91, -1));

        jLabel12.setText("Cidade*");
        jInternalFrame2.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 268, 85, 22));

        jLabel13.setText("CEP*");
        jInternalFrame2.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 43, -1));
        jInternalFrame2.getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 297, 260, -1));

        ComboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jInternalFrame2.getContentPane().add(ComboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        jButton1.setText("Fechar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jInternalFrame2.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, -1, -1));

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jInternalFrame2.getContentPane().add(txtCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 160, -1));

        jLabel14.setText("CNPJ*");
        jInternalFrame2.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 50, -1, -1));

        jPanel1.add(jInternalFrame2);
        jInternalFrame2.setBounds(270, 40, 660, 410);

        jTextField1.setBackground(new java.awt.Color(110, 105, 212));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setToolTipText("");
        jTextField1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField1InputMethodTextChanged(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(80, 170, 870, 60);

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 590, 290, 70);

        jButton5.setText("Remover");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(370, 590, 270, 70);

        jButton6.setText("Adicionar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(80, 590, 270, 70);

        jTable1.setBackground(new java.awt.Color(110, 105, 212));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Interno", "Razão Social", "Nome Fantasia", "CNPJ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(80, 240, 870, 330);

        jPanel3.setBackground(new java.awt.Color(23, 23, 23));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("CNPJ");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Nome Fantasia");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Razão Social");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(590, 140, 360, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1095, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow() != -1) {

            
            int valueID  = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            
            FornecedorDAO fdao = new FornecedorDAO();

            for (Fornecedor f : fdao.readonylID(valueID)) {

                
                    
                    txtRazaoS.setText(f.getRazao_social());
                    txtCNPJ.setText(f.getCnpj());
                    txtFantasia.setText(f.getNome_fantasia());
                    txtEndereco.setText(f.getEndereco());
                    txtNumero.setText(f.getNumero());
                    txtBairro.setText(f.getBairro());
                    txtComplemento.setText(f.getComplemento());
                    txtCidade.setText(f.getCidade());
                    ComboEstado.setSelectedItem(f.getEstado());
                    txtCep.setText(f.getCep());
                    

            }
            
            
            
            
            jInternalFrame2.setTitle("Editar - Fornecedor"); 
        
            jInternalFrame2.setVisible(true);
            jButton6.setEnabled(false);
            jButton5.setEnabled(false);
            jButton2.setEnabled(false);
            //readJTable();

        }else{
            JOptionPane.showMessageDialog(null, "Selecione um fornecedor que deseja editar");
        }

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        ScreenMenu.isInternalFrameOpen = false;     
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jButton6.setEnabled(false);
        jButton5.setEnabled(false);
        jButton2.setEnabled(false);
        jInternalFrame2.setTitle("Adicionar - Fornecedor"); 
        txtRazaoS.setText("");
        txtCNPJ.setText("");
        txtFantasia.setText("");
        txtEndereco.setText("");
        txtNumero.setText("");
        txtBairro.setText("");
        txtComplemento.setText("");
        txtCidade.setText("");
        ComboEstado.setSelectedItem("PI");
        txtCep.setText("");
        
        jInternalFrame2.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField1InputMethodTextChanged
        
        
    }//GEN-LAST:event_jTextField1InputMethodTextChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Verificar se vai adicionar ou atualizar informação
        
        if(jInternalFrame2.getTitle().equalsIgnoreCase("Adicionar - Fornecedor")){
            Fornecedor f = new Fornecedor();
            FornecedorDAO dao = new FornecedorDAO();
            if(txtRazaoS.getText().isEmpty() || txtCNPJ.getText().isEmpty() || txtFantasia.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtNumero.getText().isEmpty()
            || txtBairro.getText().isEmpty() || txtCidade.getText().isEmpty() || txtCep.getText().equalsIgnoreCase("     -   ")){
                
                JOptionPane.showMessageDialog(null, "Campos Obrigatorios não preenchidos");
                
            }else{
                f.setRazao_social(txtRazaoS.getText());
                f.setCnpj(txtCNPJ.getText());
                f.setNome_fantasia(txtFantasia.getText());
                f.setEndereco(txtEndereco.getText());
                f.setNumero(txtNumero.getText());
                f.setBairro(txtBairro.getText());
                f.setComplemento(txtComplemento.getText());
                f.setCidade(txtCidade.getText());
                f.setEstado(String.valueOf(ComboEstado.getSelectedItem()));
                f.setCep(txtCep.getText());
                dao.create(f);

                txtRazaoS.setText("");
                txtCNPJ.setText("");
                txtFantasia.setText("");
                txtEndereco.setText("");
                txtNumero.setText("");
                txtBairro.setText("");
                txtComplemento.setText("");
                txtCidade.setText("");
                ComboEstado.setSelectedItem("PI");
                txtCep.setText("");

                readJTable();
                
            
            }
        
        }
        
        if(jInternalFrame2.getTitle().equalsIgnoreCase("Editar - Fornecedor")){
            if(txtRazaoS.getText().isEmpty() || txtCNPJ.getText().isEmpty() || txtFantasia.getText().isEmpty() || txtEndereco.getText().isEmpty() || txtNumero.getText().isEmpty()
            || txtBairro.getText().isEmpty() || txtCidade.getText().isEmpty() || txtCep.getText().equalsIgnoreCase("     -   ")){
                
                JOptionPane.showMessageDialog(null, "Campos Obrigatorios não preenchidos");
                
            }else{
                int valueID  = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);

                Fornecedor f = new Fornecedor();
                FornecedorDAO dao = new FornecedorDAO();

                



                f.setRazao_social(txtRazaoS.getText());
                f.setCnpj(txtCNPJ.getText());
                f.setNome_fantasia(txtFantasia.getText());
                f.setEndereco(txtEndereco.getText());
                f.setNumero(txtNumero.getText());
                f.setBairro(txtBairro.getText());
                f.setComplemento(txtComplemento.getText());
                f.setCidade(txtCidade.getText());
                f.setEstado(String.valueOf(ComboEstado.getSelectedItem()));
                f.setCep(txtCep.getText());
                f.setId(valueID);
                dao.update(f);
                
                
            }

            
            
        
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        
        
        
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        
        if(ScreenMenu.isADM.equalsIgnoreCase("1")){
            if (jTable1.getSelectedRow() != -1) {

                Fornecedor f = new Fornecedor();
                FornecedorDAO dao = new FornecedorDAO();

                f.setId((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));

                String[] options = {"Sim", "Não"};

                int delete = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar esse fornecedor?","Pensa bem",JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

                if(delete == 0){
                    dao.delete(f); 
                }




                readJTable();

            } else {
                JOptionPane.showMessageDialog(null, "Selecione um fornecedor para excluir.");}
            
        }else{
            JOptionPane.showMessageDialog(null, "O usuario não tem permissão para deletar. Contate o ADM ");
        }
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jInternalFrame2.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton5.setEnabled(true);
        jButton2.setEnabled(true); //Botão Fechar
        jButton6.setEnabled(true);
        jInternalFrame2.setVisible(false);
        readJTable();
        jTextField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        //KEY RELEASE
        if (jRadioButton3.isSelected()){ //Buscar por Razão Social
        readJTableRazaoSocial(jTextField1.getText());
        }
        
        if (jRadioButton2.isSelected()){ //Buscar por CNPJ
        readJTableCNPJ(jTextField1.getText());
        }
        
        
        if (jRadioButton1.isSelected()){
        readJTableFantasia(jTextField1.getText());
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jInternalFrame2InternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame2InternalFrameClosing
        jButton5.setEnabled(true);
        jButton2.setEnabled(true);
        jButton6.setEnabled(true);
        readJTable();
        
        
    }//GEN-LAST:event_jInternalFrame2InternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboEstado;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRazaoS;
    // End of variables declaration//GEN-END:variables
}
